name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: python-app-websc
  AZURE_RESOURCE_GROUP: PROJECT
  AZURE_LOCATION: australiaeast
  REGISTRY_NAME: python-app-from-github-env

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ env.REGISTRY_NAME }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.REGISTRY_NAME }}.azurecr.io/websc-app:${{ github.sha }} .
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/websc-app:${{ github.sha }}
    
    - name: Create Container Apps Environment
      run: |
        az containerapp env create \
          --name websc-environment \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --location ${{ env.AZURE_LOCATION }} || echo "Environment already exists"
    
    - name: Deploy to Container Apps
      run: |
        az containerapp create \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --environment websc-environment \
          --image ${{ env.REGISTRY_NAME }}.azurecr.io/websc-app:${{ github.sha }} \
          --target-port 80 \
          --ingress external \
          --registry-server ${{ env.REGISTRY_NAME }}.azurecr.io \
          --registry-username $(az acr credential show --name ${{ env.REGISTRY_NAME }} --query username --output tsv) \
          --registry-password $(az acr credential show --name ${{ env.REGISTRY_NAME }} --query passwords[0].value --output tsv) || \
        az containerapp update \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --image ${{ env.REGISTRY_NAME }}.azurecr.io/websc-app:${{ github.sha }}
